// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.dani2bes.jotitdown.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.dani2bes.jotitdown.domain.NoteUser;
import org.dani2bes.jotitdown.domain.NoteUserDataOnDemand;
import org.dani2bes.jotitdown.repository.NoteUserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NoteUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NoteUserDataOnDemand: @Component;
    
    private Random NoteUserDataOnDemand.rnd = new SecureRandom();
    
    private List<NoteUser> NoteUserDataOnDemand.data;
    
    @Autowired
    NoteUserRepository NoteUserDataOnDemand.noteUserRepository;
    
    public NoteUser NoteUserDataOnDemand.getNewTransientNoteUser(int index) {
        NoteUser obj = new NoteUser();
        setEmail(obj, index);
        setPassword(obj, index);
        return obj;
    }
    
    public void NoteUserDataOnDemand.setEmail(NoteUser obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void NoteUserDataOnDemand.setPassword(NoteUser obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public NoteUser NoteUserDataOnDemand.getSpecificNoteUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        NoteUser obj = data.get(index);
        Long id = obj.getId();
        return noteUserRepository.findOne(id);
    }
    
    public NoteUser NoteUserDataOnDemand.getRandomNoteUser() {
        init();
        NoteUser obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return noteUserRepository.findOne(id);
    }
    
    public boolean NoteUserDataOnDemand.modifyNoteUser(NoteUser obj) {
        return false;
    }
    
    public void NoteUserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = noteUserRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'NoteUser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<NoteUser>();
        for (int i = 0; i < 10; i++) {
            NoteUser obj = getNewTransientNoteUser(i);
            try {
                noteUserRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            noteUserRepository.flush();
            data.add(obj);
        }
    }
    
}
